import type { Product } from "./types";

// Development adapter only. Production reads the same shape from Supabase.
export const demoProducts: Product[] = [
  {
    id: "p-001",
    slug: "linen-ease-shirt",
    title: { en: "Linen Ease Shirt", ar: "قميص كتان مريح" },
    category: "men",
    price: 129900,
    color: "#c8b298",
    colorName: { en: "Oat", ar: "شوفان" },
    sizes: ["S", "M", "L", "XL"],
    badge: "new",
    art: "sand",
  },
  {
    id: "p-002",
    slug: "soft-structure-vest",
    title: { en: "Soft Structure Vest", ar: "صديري بقصّة ناعمة" },
    category: "women",
    price: 109900,
    compareAt: 139900,
    color: "#ede5d5",
    colorName: { en: "Bone", ar: "عاجي" },
    sizes: ["XS", "S", "M", "L"],
    badge: "sale",
    art: "clay",
  },
  {
    id: "p-003",
    slug: "wide-leg-trouser",
    title: { en: "Fluid Wide-Leg Trouser", ar: "بنطلون واسع انسيابي" },
    category: "women",
    price: 149900,
    color: "#3e4532",
    colorName: { en: "Olive", ar: "زيتوني" },
    sizes: ["S", "M", "L"],
    badge: "new",
    art: "olive",
  },
  {
    id: "p-004",
    slug: "everyday-overshirt",
    title: { en: "Everyday Overshirt", ar: "أوفرشيرت يومي" },
    category: "men",
    price: 159900,
    color: "#282725",
    colorName: { en: "Ink", ar: "حبري" },
    sizes: ["M", "L", "XL", "2XL"],
    badge: "low",
    art: "ink",
  },
];
