create table public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null check (provider in ('paymob')),
  provider_event_id text not null,
  order_id uuid references public.orders(id) on delete set null,
  transaction_id text,
  external_order_id text,
  integration_id bigint,
  amount_minor bigint check (amount_minor is null or amount_minor >= 0),
  currency text,
  payload_digest text not null check (payload_digest ~ '^[a-f0-9]{64}$'),
  outcome text not null default 'received'
    check (outcome in ('received', 'processed', 'ignored', 'rejected')),
  error_code text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider, provider_event_id)
);

create index payment_webhook_events_order_received_idx
  on public.payment_webhook_events (order_id, received_at desc);

alter table public.payment_webhook_events enable row level security;
revoke all on public.payment_webhook_events from anon, authenticated;
grant select on public.payment_webhook_events to authenticated;
grant all on public.payment_webhook_events to service_role;
grant usage, select on sequence public.payment_webhook_events_id_seq to service_role;

create policy payment_webhook_events_staff_select
on public.payment_webhook_events for select to authenticated
using (
  (select private.has_any_role(
    array['support','analyst','admin','super_admin']::public.app_role[]
  ))
);

create or replace function public.admin_update_order(
  p_order_id uuid,
  p_status public.order_status,
  p_payment_status public.payment_status,
  p_note text default null,
  p_shipment_number text default null,
  p_courier text default null,
  p_tracking_url text default null,
  p_proof_status text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := (select auth.uid());
  v_previous public.orders%rowtype;
  v_line record;
  v_status public.order_status := p_status;
  v_payment_status public.payment_status := p_payment_status;
  v_proofs_updated integer := 0;
begin
  if v_actor is null or not (select private.has_any_role(array['support','warehouse','admin','super_admin']::public.app_role[])) then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;
  if p_proof_status is not null and p_proof_status not in ('approved', 'rejected') then
    raise exception 'INVALID_PROOF_STATUS' using errcode = '22023';
  end if;
  if p_proof_status is not null and not (select private.has_any_role(array['support','admin','super_admin']::public.app_role[])) then
    raise exception 'PROOF_REVIEW_FORBIDDEN' using errcode = '42501';
  end if;

  select * into v_previous from public.orders where id = p_order_id for update;
  if v_previous.id is null then raise exception 'ORDER_NOT_FOUND' using errcode = 'P0002'; end if;
  if v_previous.status in ('cancelled', 'returned') and p_status <> v_previous.status then
    raise exception 'TERMINAL_ORDER' using errcode = 'P0001';
  end if;

  if p_proof_status is not null then
    if v_previous.payment_method not in ('cod', 'vodafone_cash', 'instapay') then
      raise exception 'PROOF_NOT_SUPPORTED' using errcode = '22023';
    end if;

    update public.payment_proofs set
      status = p_proof_status,
      reviewer_id = v_actor,
      review_note = nullif(trim(p_note), ''),
      reviewed_at = now()
    where order_id = p_order_id and status = 'pending';
    get diagnostics v_proofs_updated = row_count;
    if v_proofs_updated = 0 then
      raise exception 'PROOF_NOT_PENDING' using errcode = 'P0001';
    end if;

    if p_proof_status = 'approved' then
      v_status := 'confirmed';
      v_payment_status := case
        when v_previous.payment_method = 'cod' then 'cod_due'::public.payment_status
        else 'paid'::public.payment_status
      end;
    else
      v_status := 'payment_review';
      v_payment_status := 'rejected';
    end if;
  elsif v_previous.payment_method in ('cod', 'vodafone_cash', 'instapay')
    and v_previous.payment_status = 'proof_submitted'
    and p_payment_status in ('paid', 'cod_due') then
    raise exception 'PROOF_APPROVAL_REQUIRED' using errcode = 'P0001';
  end if;

  if v_previous.payment_method = 'paymob'
    and v_previous.payment_status <> 'paid'
    and v_payment_status = 'paid' then
    raise exception 'PAYMOB_WEBHOOK_REQUIRED' using errcode = 'P0001';
  end if;
  if v_status in ('shipped', 'out_for_delivery') and coalesce(trim(p_shipment_number), '') = '' then
    raise exception 'SHIPMENT_NUMBER_REQUIRED' using errcode = '22023';
  end if;

  if v_status = 'cancelled' and v_previous.status not in ('cancelled', 'delivered', 'returned') then
    for v_line in select variant_id, quantity from public.order_items where order_id = p_order_id and variant_id is not null loop
      update public.inventory set reserved = greatest(0, reserved - v_line.quantity), updated_at = now()
      where variant_id = v_line.variant_id;
      insert into public.inventory_movements (variant_id, movement_type, quantity_delta, reference_type, reference_id, reason, actor_id)
      values (v_line.variant_id, 'release', -v_line.quantity, 'order', p_order_id::text, 'Order cancelled', v_actor);
    end loop;
  elsif v_status = 'delivered' and v_previous.status <> 'delivered' then
    for v_line in select variant_id, quantity from public.order_items where order_id = p_order_id and variant_id is not null loop
      update public.inventory set on_hand = on_hand - v_line.quantity, reserved = greatest(0, reserved - v_line.quantity), updated_at = now()
      where variant_id = v_line.variant_id and on_hand >= v_line.quantity;
      if not found then raise exception 'INSUFFICIENT_STOCK_AT_FULFILMENT' using errcode = 'P0001'; end if;
      insert into public.inventory_movements (variant_id, movement_type, quantity_delta, reference_type, reference_id, reason, actor_id)
      values (v_line.variant_id, 'sale', -v_line.quantity, 'order', p_order_id::text, 'Order delivered', v_actor);
    end loop;
  end if;

  update public.orders set
    status = v_status,
    payment_status = v_payment_status,
    shipment_number = nullif(trim(p_shipment_number), ''),
    courier = nullif(trim(p_courier), ''),
    tracking_url = nullif(trim(p_tracking_url), ''),
    paid_at = case when v_payment_status in ('paid', 'cod_collected') then coalesce(paid_at, now()) else paid_at end,
    shipped_at = case when v_status in ('shipped', 'out_for_delivery', 'delivered') then coalesce(shipped_at, now()) else shipped_at end,
    delivered_at = case when v_status = 'delivered' then coalesce(delivered_at, now()) else delivered_at end,
    cancelled_at = case when v_status = 'cancelled' then coalesce(cancelled_at, now()) else cancelled_at end,
    updated_at = now()
  where id = p_order_id;

  insert into public.order_status_history (order_id, status, payment_status, note, actor_id)
  values (
    p_order_id,
    v_status,
    v_payment_status,
    coalesce(
      nullif(trim(p_note), ''),
      case p_proof_status
        when 'approved' then 'Payment proof approved'
        when 'rejected' then 'Payment proof rejected'
        else null
      end
    ),
    v_actor
  );
end;
$$;

revoke execute on function public.admin_update_order(uuid, public.order_status, public.payment_status, text, text, text, text, text) from public, anon;
grant execute on function public.admin_update_order(uuid, public.order_status, public.payment_status, text, text, text, text, text) to authenticated;

drop function public.process_paymob_callback(text, text, text, boolean, bigint);

create function public.process_paymob_callback(
  p_event_id text,
  p_order_number text,
  p_transaction_id text,
  p_external_order_id text,
  p_integration_id bigint,
  p_success boolean,
  p_amount_minor bigint,
  p_currency text,
  p_payload_digest text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_id bigint;
  v_order public.orders%rowtype;
  v_outcome text;
  v_error_code text;
begin
  if coalesce(trim(p_event_id), '') = ''
    or coalesce(trim(p_transaction_id), '') = ''
    or p_payload_digest !~ '^[a-f0-9]{64}$' then
    raise exception 'INVALID_WEBHOOK_IDENTITY' using errcode = '22023';
  end if;

  insert into public.payment_webhook_events (
    provider, provider_event_id, transaction_id, external_order_id, integration_id,
    amount_minor, currency, payload_digest
  ) values (
    'paymob', trim(p_event_id), trim(p_transaction_id),
    nullif(trim(p_external_order_id), ''), p_integration_id,
    p_amount_minor, upper(trim(p_currency)),
    lower(p_payload_digest)
  )
  on conflict (provider, provider_event_id) do nothing
  returning id into v_event_id;

  if v_event_id is null then
    return jsonb_build_object('outcome', 'duplicate');
  end if;

  select * into v_order
  from public.orders
  where order_number = trim(p_order_number)
  for update;

  if v_order.id is null or v_order.payment_method <> 'paymob' then
    v_outcome := 'rejected';
    v_error_code := 'ORDER_NOT_FOUND';
  elsif upper(trim(p_currency)) <> 'EGP' then
    v_outcome := 'rejected';
    v_error_code := 'PAYMENT_CURRENCY_MISMATCH';
  elsif p_amount_minor <> v_order.total_minor then
    v_outcome := 'rejected';
    v_error_code := 'PAYMENT_AMOUNT_MISMATCH';
  elsif coalesce(v_order.paymob_order_id, '') <> ''
    and coalesce(trim(p_external_order_id), '') <> v_order.paymob_order_id then
    v_outcome := 'rejected';
    v_error_code := 'PAYMOB_ORDER_MISMATCH';
  elsif v_order.payment_status = 'paid' then
    v_outcome := 'ignored';
    v_error_code := case
      when v_order.paymob_transaction_id = trim(p_transaction_id) then 'ALREADY_PAID'
      else 'ADDITIONAL_TRANSACTION_AFTER_PAYMENT'
    end;
  else
    update public.orders set
      paymob_transaction_id = trim(p_transaction_id),
      paymob_order_id = coalesce(nullif(trim(p_external_order_id), ''), paymob_order_id),
      payment_status = case when p_success then 'paid'::public.payment_status else 'failed'::public.payment_status end,
      status = case when p_success then 'confirmed'::public.order_status else status end,
      paid_at = case when p_success then coalesce(paid_at, now()) else paid_at end,
      reservation_expires_at = case when p_success then null else reservation_expires_at end,
      updated_at = now()
    where id = v_order.id;

    insert into public.order_status_history (order_id, status, payment_status, note)
    values (
      v_order.id,
      case when p_success then 'confirmed'::public.order_status else v_order.status end,
      case when p_success then 'paid'::public.payment_status else 'failed'::public.payment_status end,
      case when p_success then 'Payment confirmed by Paymob webhook' else 'Paymob payment failed' end
    );
    v_outcome := 'processed';
  end if;

  update public.payment_webhook_events set
    order_id = v_order.id,
    outcome = v_outcome,
    error_code = v_error_code,
    processed_at = now()
  where id = v_event_id;

  return jsonb_build_object('outcome', v_outcome, 'code', v_error_code);
end;
$$;

revoke execute on function public.process_paymob_callback(text, text, text, text, bigint, boolean, bigint, text, text) from public, anon, authenticated;
grant execute on function public.process_paymob_callback(text, text, text, text, bigint, boolean, bigint, text, text) to service_role;
